version: "3"
services:
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=caluma
      - POSTGRES_PASSWORD=caluma
    volumes:
      - dbdata:/var/lib/postgresql/data

  caluma:
    image: projectcaluma/caluma:latest@sha256:13963a3dd6fc73636117dd321d2d600486905369c277e5d746a8da1cee61a8f4
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - ENV=docker
      #- MINIO_STORAGE_ENDPOINT=localhost:9000

  minio:
      image: minio/minio:latest@sha256:7ec09db11d048c48e3d63d507fda56feeb26d1dba317d082e774567fe49ff32d
      volumes:
        - minio_data:/data
      ports:
        - "9000:9000"
      environment:
        - MINIO_ACCESS_KEY=minio
        - MINIO_SECRET_KEY=minio123
        - MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET=True
      command: server data

volumes:
  dbdata:
  minio_data: